### ISSUE TITLE
NewsReader schreibt Seitentitel nicht um

### ISSUE THREAD

**Issue by christianbarkowsky** [psi-4ward/news4ward#66]
NewsReader ersetzt den Seitentitel nicht mit dem Beitragstitel.

**Comment by frontendschlampe** [comment]
Ist das bei Dir noch immer so @christianbarkowsky? Ich kann das in meiner Installation hier nämlich nicht nachvollziehen!

**Comment by christianbarkowsky** [comment]
@frontendschlampe jop ... ist noch so. http://christianbarkowsky.de/blog/post/mein-kreativer-ausgleich.html

**Comment by psi-4ward** [comment]
Contao unterscheidet zwischen `title` und `pageTitle` wobei letzterer eine höhere Priorität hat.
News4ward-Reader setzt aber den `title`, wenn bei der Seite ein `pageTitle` hinterlegt ist wird dieser genommen.

Siehe auch `news4ward_metatitle`
