### ISSUE TITLE
cssID nicht korrekt ausgegeben

### ISSUE THREAD

**Issue by Flaschenzug** [psi-4ward/news4ward#76]
Wie es aussieht, wird bei mir die cssID nicht korrekt ausgegeben / bzw. konvertiert.
Folgender Ausgabe erhalte ich im Quelltext: a:2:{i:0;s:0:"";i:1;s:0:"";}

<div class="... first even" a:2:{i:0;s:0:"";i:1;s:0:"";}="">CONTENT</div>

Irgend eine Idee woran das liegen könnte?

**Comment by psi-4ward** [comment]
ja hab ich, wo liegt das Problem genau? Reader? Liste?
Hast nen Link?

**Comment by Flaschenzug** [comment]
Liste. Mit leicht modifiziertem Template.
Leider nicht online verfügbar.

**Comment by psi-4ward** [comment]
Paste mir mal dein Template - das scheint ja angepasst zu sein

**Comment by Flaschenzug** [comment]
<div class="newsitem col-xs-6 col-sm-12 col-md-6 col-lg-4 <?php echo $this->class; ?>"<?php echo $this->cssID; ?>>

<div class="boxContent" onclick="location.href='<?php echo $this->link; ?>';">

  <div class="contentbox-infobar">
  	<h2><a href="<?php echo $this->link; ?>"><?php echo $this->title; ?></a></h2>
  </div>

</div>
</div>

**Comment by Flaschenzug** [comment]
Perfekt, jetzt läuft es. (Zumindest wird das ganze nicht mehr ausgegeben.)
Danke.
