### ISSUE TITLE
 Fatal error: Weiterleitungsseite und Listen-Seite

### ISSUE THREAD

**Issue by profimedien** [psi-4ward/news4ward#83]
Fatal error: Class 'News4wardModel' not found in .../system/modules/core/controllers/BackendPage.php on line 87

Das erscheint bei einem Nachrichtenarchiv, bei dem man eine Weiterleitungsseite und/oder Listen-Seite auswählen möchte.

**Comment by psi-4ward** [comment]
Bitte mit aktuellen Versionen testen, ich konnte den Fehler eben nicht nachstellen
