### ISSUE TITLE
Beitragsliste - Sortierreihenfolge: zufällig?

### ISSUE THREAD

**Issue by Stefko** [psi-4ward/news4ward#88]
Wäre es machbar, bei der Sortierreihenfolge neben Datum und Titel auch noch die Möglichkeit zu schaffen, die Artikel in zufälliger Reihenfolge auszugeben?

**Comment by psi-4ward** [comment]
Bitte testen und Rückmeldung geben !

**Comment by Stefko** [comment]
Funktioniert perfekt. Vielen Dank für die schnelle Hilfe :-)
