### ISSUE TITLE
Cannot use 'String' as class name with PHP 7

### ISSUE THREAD

**Issue by sizta** [psi-4ward/news4ward#89]
I get the following error with PHP 7 :

PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /xxx/xxx/xxxx/system/modules/core/library/Contao/String.php on line 28

**Comment by psi-4ward** [comment]
Gibts nen Stacktrace dazu?

**Comment by psi-4ward** [comment]
https://github.com/contao/core-bundle/issues/309

**Comment by psi-4ward** [comment]
closed by 808974b259f876bcef359f4cf160c45576b1207c
