### ISSUE TITLE
Fragen zur Weiterentwicklung

### ISSUE THREAD

**Issue by fenepedia** [psi-4ward/news4ward#93]
Hallo PSI,

könntest du kurz sagen, wie die Pläne bezüglich der Weiterentwicklung von news4ward aussieht?

- Kompatibilität mit PHP 7?
- Kompatibilität mit Contao 4?
- neue Features?

**Comment by frontendschlampe** [comment]
@psi-4ward wird an der Erweiterung sicherlich nicht mehr viel machen, da er leider nicht mehr viel mit Contao zu tun hat.

Aktuell pflegen wir die Erweiterung soweit wir Bedarf/Budget haben.

Das Problem ist, dass die Erweiterung eigentlich nicht mehr so wirklich benötigt wird, da ja Contao die Hauptfunktion (CE innerhalb einer News) mittlerweile als Corefunktion mitbringt.

Aber wir sind für alle Ideen offen und zu Gesprächen bereit! :-)

**Comment by psi-4ward** [comment]
Genau so ist es. Auftragsbezogen würde ich schon noch was machen.
PHP7 Kompatibel müsste der News4ward Stack sein.

**Comment by fenepedia** [comment]
Danke für die Info.

PHP7 funktioniert leider nicht, hier kommt es zu Fehlermeldungen.

<code>PHP Fatal error: Uncaught exception 'Error' with message 'Function name must be a string' thrown in /system/modules/news4ward/Module/Listing.php on line 95</code>

Ich nutze die Erweiterung wegen folgenden Features:

- Kategorien zu jedem Artikel zuordnen
- eigenen Meta-Titel vergeben (SEO)
- OpenGraph-Daten für Facebook

Hab mich gerade mal nach Alternativen umgesehen. Ich werde das erst mal testen:
- Kategorien -> [news_categories]
- Meta-Titel -> kann ich wohl selber über eine kleine Erweiterung lösen
- OpenGrapp-Daten > selber über das Template oder [og_tags]

Damit können wir das Thema wohl beenden.

**Comment by psi-4ward** [comment]
Hast du nen Stacktrace zu deinem Error? Klingt mir nicht nach nem PHP7 Problem!
Iwo wird blödsinn in `$GLOBALS['TL_HOOKS']['News4wardListFilter']` geschrieben

**Comment by fenepedia** [comment]
Wie kann ich einen Stacktrace erstellen? Oder meinst du die komplette error.log?

**Comment by bibib** [comment]
Gibt's zum Stacktrace schon neue Erkenntnisse? Bzw. wie hoch wären denn die Kosten für eine Anpassung für C4? Ich hätte schon einige Kunden, die das brauchen könnten und wenn es insgesamt günstiger wäre als ein Umstieg auf das News-Modul, wäre das vielleicht eine Option.

**Comment by psi-4ward** [comment]
Nen Stacktrace hab ich nie erhalten und auch keine weiteren Logs o.Ä.

Anpassung für Contao 4: Siehe meinen Kommentar von table4ward.

**Comment by fenepedia** [comment]
Aufgrund der fehlenden Weiterentwicklung habe ich alle aktuellen news4ward Seiten auf das normale Contao News-Modul geändert.

@bibib Im Moment ist die Erweiterung nicht PHP7 kompatibel.
Das "Problem Function name must be a string".

Evtl. reicht es, wenn du den Code komplett nach diesem Aufruf durchsuchst und änderst.
https://community.contao.org/de/showthread.php?72297-PHP-7-Function-name-must-be-a-string-gt-call_user_func_array&p=484745&viewfull=1#post484745

**Comment by bibib** [comment]
Danke für den Hinweis - scheinbar braucht es wirklich nur wenige Änderungen: https://community.contao.org/de/showthread.php?72234-news4ward-und-Contao-4-4&p=493144#post493144
> Evtl. reicht es, wenn du den Code komplett nach diesem Aufruf durchsuchst und änderst.
> https://community.contao.org/de/showthread.php?72297-PHP-7-Function-name-must-be-a-string-gt-call_user_func_array&p=484745&viewfull=1#post484745

Danke für den Hinweis - scheinbar braucht es wirklich nur wenige Änderungen: https://community.contao.org/de/showthread.php?72234-news4ward-und-Contao-4-4&p=493144#post493144

**Comment by psi-4ward** [comment]
Hab mal nen commit 12c5577 gemacht, bitte testen ;)

**Comment by bibib** [comment]
Sieht gut aus, nur die Icons aus dem html-Ordner fehlen noch. :-)
Lokal habe ich den Ordner html in assets umbenannt und die Pfade entsprechend angepasst.
- in dca/tl_news4ward_article.php
- in config/config.php

**Comment by psi-4ward** [comment]
Okay? Mir nicht klar warum das so muss aber habs mal umbenannt.

**Comment by bibib** [comment]
Mir auch nicht, aber Spooky wird's schon wissen. ;-)
Die Icons sind da, ich musste aber das Teaserbild neu zuordnen? Lässt sich das irgendwie verhindern?

**Comment by xchs** [comment]
Ich war auch der Meinung, dass eigentlich beide Ordnernamen funktionieren sollten.

**Comment by psi-4ward** [comment]
Teaserbild?? Hier hat sich nichts verändert.

**Comment by bibib** [comment]
Na, passt schon. In Contao 3.5 ist auch alles paletti. Vielen Dank für die Anpassung!

**Comment by bibib** [comment]
Sorry, muss nochmal öffnen. Spooky fragt, ob du die Erweiterung bitte auch noch für Contao 4 freigeben könntest?

**Comment by bibib** [comment]
Muss leider nochmal aufschnüren ... im Contao-Manager wird die Erweiterung immer noch als inkompatibel angezeigt. Könntest du das bitte auch noch richten? Bzw. ist die Anpassung auch unter Contao 3.5 im Composer nicht auswählbar.

**Comment by psi-4ward** [comment]
Normal updated sich doch pakagist selbst? Hab mal auf update gedrückt

**Comment by frontendschlampe** [comment]
> Normal updated sich doch pakagist selbst? Hab mal auf update gedrückt

Die Einbindung hat sich doch geändert! ;-)

**Comment by psi-4ward** [comment]
Aja? Meine Docker-Registry und Travis Hooks funzen auch noch.
