### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by sizta** [psi-4ward/news4ward#98]
Could you generate  release tags for the updated news4ward reps? 

Composer still complains during the installation via Contao Manager: 
https://community.contao.org/de/showthread.php?72234-news4ward-und-Contao-4-4&p=494709&viewfull=1#post494709

**Comment by psi-4ward** [comment]
done, pls test

**Comment by sizta** [comment]
Yes, works like a charm.

Please can you do the same for the other reps like  ...tags, ...archive_menu, ...categories, ...comments, ...newsletter, and  ...related ?

Thanks a lot!!

**Comment by psi-4ward** [comment]
did it already
